program: sweep.py
name: ehrsqlswitchingsweep
method: grid
metric:
  goal: minimize
  name: execution_accuracy
parameters:
  top_k_tokens:
    values: [0, 5, 10, 15, 20, 25]
  top_p_tokens:
    values: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  top_k_experts:
    values: [0, 1, 2, 3, 4, 5, 7, 10, 15, 20, 25]
  top_p_experts:
    values: [0.0, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
