program: sweep.py
name: ehrsqlswitchingsweep
method: grid
metric:
  goal: minimize
  name: execution_accuracy
parameters:
  top_k_tokens:
    values: [0, 5, 10, 20, 40]
  top_p_tokens:
    values: [0.0, 0.2, 0.4, 0.6, 0.8]
  top_k_experts:
    values: [0, 1, 2, 4, 8, 16]
  top_p_experts:
    values: [0.0, 0.1, 0.2, 0.4, 0.6, 0.8]
